### ISSUE TITLE
[Critical vuln] Exposure of Sensitive Information in eventsource

### ISSUE THREAD

**Issue by cq-fpietron** [sanity-io/eventsource#2]
Hello,

`@sanity/client` and other sanity packages report critical vulnerabilities which originate from `eventsource`. It was patched in the root package, but not in this one / sanity packages that depend on `@sanity/eventsource`. Are there plans to update this chain of packages as well, or maybe there's another way to handle it?

@rexxars mentioning you as I've noticed you're maintaining both packages

https://github.com/advisories/GHSA-6h5x-7c5m-7cr7

**Comment by sgrzemski** [comment]
Aw yes, +1 to that.

**Comment by GlenCodes** [comment]
+1 to that also

**Comment by petertflem** [comment]
+1 to this

**Comment by kmelve** [comment]
Thanks for reporting!

It's not really an issue for us since it affects just redirects and we're only using hardcoded URLs. It can be automatically fixed by reinstalling dependencies without a lock file. We'll include a patch in the next release in a week or so.

**Comment by rexxars** [comment]
As @kmelve outlines here - this never directly affected the use of this module inside of the _sanity client_, since it uses specific URLs that we control. However, given this module is available to use in other projects outside of Sanity, we of course want to make sure it is patched with the latest security fixes.

Given this, we have published:
- `@sanity/eventsource` v3.0.2, which upgrades `eventsource` to `v1.1.1` and is semver-compatible.
- `@sanity/eventsource` v4.0.0, which upgrades `eventsource` to `v2.0.2`, but requires node v12 and is thus technically a breaking change should you be using older versions of node.
- `@sanity/client` v3.3.1, which upgrades `@sanity/eventsource` to `v2.0.2` (while we previously depended on the v1 range and now upgraded to v2, the client has required node 12 for some time, so this _should_ be considered within the defined compatibility and thus not considered breaking)

I have also made a pull requests against the GitHub advisory repository to fix an issue with the CVE, where the fix available in the v1 range (`v1.1.1`) was not marked properly.
